export const devicesConstants = {
    FIRM_DEVICES_GET_REQUEST: "FIRM_DEVICES_GET_REQUEST",
    FIRM_DEVICES_GET_SUCCESS: "FIRM_DEVICES__GET_SUCCESS",
    FIRM_DEVICES_GET_FAILURE: "FIRM_DEVICES__GET_FAILURE",

    CLEAN_DEVICES_ERRORS: 'CLEAN_DEVICES_ERRORS',
    CLEAN_DEVICES_SUCCESS: 'CLEAN_DEVICES_SUCCESS',

    UPDATE_DEVICE_REQUEST: "UPDATE_DEVICE_REQUEST",
    UPDATE_DEVICE_SUCCESS: "UPDATE_DEVICE_SUCCESS",
    UPDATE_DEVICE_FAILURE: "UPDATE_DEVICE_FAILURE",

    ADD_DEVICE_REQUEST: 'ADD_DEVICE_REQUEST',
    ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
    ADD_DEVICE_FAILURE: 'ADD_DEVICE_FAILURE',

    DELETE_DEVICE_REQUEST: 'DELETE_DEVICE_REQUEST',
    DELETE_DEVICE_SUCCESS: 'DELETE_DEVICE_SUCCESS',
    DELETE_DEVICE_FAILURE: 'DELETE_DEVICE_FAILURE'
};
