export const devicesConstants = {
    FIRM_DEVICES_GET_REQUEST: "FIRM_DEVICES_GET_REQUEST",
    FIRM_DEVICES_GET_SUCCESS: "FIRM_DEVICES_GET_SUCCESS",
    FIRM_DEVICES_GET_FAILURE: "FIRM_DEVICES_GET_FAILURE",

    USER_DEVICES_GET_REQUEST: "USER_DEVICES_GET_REQUEST",
    USER_DEVICES_GET_SUCCESS: "USER_DEVICES_GET_SUCCESS",
    USER_DEVICES_GET_FAILURE: "USER_DEVICES_GET_FAILURE",

    CLEAN_DEVICES_ERRORS: 'CLEAN_DEVICES_ERRORS',
    CLEAN_DEVICES_SUCCESS: 'CLEAN_DEVICES_SUCCESS',

    UPDATE_DEVICE_USERS_REQUEST: "UPDATE_DEVICE_USERS_REQUEST",
    UPDATE_DEVICE_USERS_SUCCESS: "UPDATE_DEVICE_USERS_SUCCESS",
    UPDATE_DEVICE_USERS_FAILURE: "UPDATE_DEVICE_USERS_FAILURE",

    ADD_USER_DEVICE_REQUEST: 'ADD_USER_DEVICE_REQUEST',
    ADD_USER_DEVICE_SUCCESS: 'ADD_USER_DEVICE_SUCCESS',

    ADD_FIRM_DEVICE_REQUEST: 'ADD_FIRM_DEVICE_REQUEST',
    ADD_FIRM_DEVICE_SUCCESS: 'ADD_FIRM_DEVICE_SUCCESS',

    ADD_DEVICE_FAILURE: 'ADD_DEVICE_FAILURE',

    DELETE_USER_DEVICE_REQUEST: 'DELETE_USER_DEVICE_REQUEST',
    DELETE_USER_DEVICE_SUCCESS: 'DELETE_USER_DEVICE_SUCCESS',

    DELETE_FIRM_DEVICE_REQUEST: 'DELETE_FIRM_DEVICE_REQUEST',
    DELETE_FIRM_DEVICE_SUCCESS: 'DELETE_FIRM_DEVICE_SUCCESS',

    DELETE_DEVICE_FAILURE: 'DELETE_DEVICE_FAILURE',

    UPDATE_USER_DEVICE_REQUEST: 'UPDATE_USER_DEVICE_REQUEST',
    UPDATE_USER_DEVICE_SUCCESS: 'UPDATE_USER_DEVICE_SUCCESS',
    UPDATE_USER_DEVICE_FAILURE: 'UPDATE_USER_DEVICE_FAILURE',

    UPDATE_FIRM_DEVICE_REQUEST: 'UPDATE_FIRM_DEVICE_REQUEST',
    UPDATE_FIRM_DEVICE_SUCCESS: 'UPDATE_FIRM_DEVICE_SUCCESS',
    UPDATE_FIRM_DEVICE_FAILURE: 'UPDATE_FIRM_DEVICE_FAILURE'
};
