export const firmConstants = {
    FIRMS_GET_REQUEST: "FIRMS_GET_REQUEST",
    FIRMS_GET_SUCCESS: "FIRMS_GET_SUCCESS",
    FIRMS_GET_FAILURE: "FIRMS_GET_FAILURE",

    CLEAN_FIRMS_ERRORS: 'CLEAN_FIRMS_ERRORS',
    CLEAN_FIRMS_SUCCESS: 'CLEAN_FIRMS_SUCCESS',

    UPDATE_FIRM_REQUEST: "UPDATE_FIRM_REQUEST",
    UPDATE_FIRM_SUCCESS: "UPDATE_FIRM_SUCCESS",
    UPDATE_FIRM_FAILURE: "UPDATE_FIRM_FAILURE",

    ADD_FIRM_REQUEST: 'ADD_FIRM_REQUEST',
    ADD_FIRM_SUCCESS: 'ADD_FIRM_SUCCESS',
    ADD_FIRM_FAILURE: 'ADD_FIRM_FAILURE',
};
