export const firmConstants = {
    FIRMS_GET_REQUEST: "FIRMS_GET_REQUEST",
    FIRMS_GET_SUCCESS: "FIRMS_GET_SUCCESS",
    FIRMS_GET_FAILURE: "FIRMS_GET_FAILURE",

    CLEAN_FIRMS_ERRORS: 'CLEAN_FIRMS_ERRORS',
    CLEAN_FIRMS_SUCCESS: 'CLEAN_FIRMS_SUCCESS'
};
