export const userConstants = {
    USERS_GET_REQUEST: "USERS_GET_REQUEST",
    USERS_GET_SUCCESS: "USERS_GET_SUCCESS",
    USERS_GET_FAILURE: "USERS_GET_FAILURE",

    CLEAN_USERS_ERRORS: 'CLEAN_USERS_ERRORS',
    CLEAN_USERS_SUCCESS: 'CLEAN_USERS_SUCCESS',

    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'ADD_USER_FAILURE',

    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE'
};
