export const dataConstants = {
    TIME_GET_REQUEST: "TIME_GET_REQUEST",
    TIME_GET_REQUEST_SUCCESS: "TIME_GET_REQUEST_SUCCESS",
    TIME_GET_REQUEST_FAILURE: "TIME_GET_REQUEST_FAILURE",

    DATA_GET_REQUEST: "DATA_GET_REQUEST",
    DATA_GET_REQUEST_SUCCESS: "DATA_GET_REQUEST_SUCCESS",
    DATA_GET_REQUEST_FAILURE: "DATA_GET_REQUEST_FAILURE",

    CLEAN_DATA_ERRORS: 'CLEAN_DATA_ERRORS',
    CLEAN_DATA_SUCCESS: 'CLEAN_DATA_SUCCESS',
};
