export const loginConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',

    CHANGE_PASS_REQUEST: "CHANGE_PASS_REQUEST",
    CHANGE_PASS_SUCCESS: "CHANGE_PASS_SUCCESS",
    CHANGE_PASS_FAILURE: "CHANGE_PASS_FAILURE",

    SET_USER: 'SET_USER',
    CLEAN_LOGIN_ERRORS: 'CLEAN_LOGIN_ERRORS',
    CLEAN_LOGIN_SUCCESS: 'CLEAN_LOGIN_SUCCESS'
};
